# Generated by Django 2.1.7 on 2019-03-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlocation',
            old_name='event',
            new_name='event_id',
        ),
    ]
