# Generated by Django 2.1.7 on 2019-03-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mgmt', '0002_auto_20190309_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='<add description here>'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default='2020-01-01'),
        ),
    ]
