# Generated by Django 2.1.7 on 2019-03-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mgmt', '0003_auto_20190309_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='description',
            field=models.TextField(default='<add description here>'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='localization',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eventrole',
            name='description',
            field=models.TextField(default='<add description here>'),
        ),
        migrations.AddField(
            model_name='locationtask',
            name='description',
            field=models.TextField(default='<add description here>'),
        ),
    ]
